## Base de dados sobre cancer ##
 
O objetivo e trbalhar os conceitos iniciais sobre redes neurais e suas arquiteturas mais simples

In [1]:
import pandas as pd
df_input = pd.read_csv('entradas-breast.csv')
df_output = pd.read_csv('saidas-breast.csv')
df_input.head()

radius_mean   texture_mean   perimeter_mean   area_mean   smoothness_mean  \
0         17.99          10.38           122.80      1001.0           0.11840   
1         20.57          17.77           132.90      1326.0           0.08474   
2         19.69          21.25           130.00      1203.0           0.10960   
3         11.42          20.38            77.58       386.1           0.14250   
4         20.29          14.34           135.10      1297.0           0.10030   

    compactness_mean   concavity_mean  concave_points_mean   symmetry_mean  \
0            0.27760           0.3001              0.14710          0.2419   
1            0.07864           0.0869              0.07017          0.1812   
2            0.15990           0.1974              0.12790          0.2069   
3            0.28390           0.2414              0.10520          0.2597   
4            0.13280         198.0000              0.10430          0.1809   

    fractal_dimension_mean  ...   radius_worst   texture_worst  \
0                  0.07871  ...          25.38           17.33   
1                  0.05667  ...          24.99           23.41   
2                  0.05999  ...          23.57           25.53   
3                  0.09744  ...          14.91           26.50   
4                  0.05883  ...          22.54           16.67   

    perimeter_worst   area_worst   smoothness_worst   compactness_worst  \
0            184.60       2019.0             0.1622              0.6656   
1            158.80       1956.0             0.1238              0.1866   
2            152.50       1709.0             0.1444              0.4245   
3             98.87        567.7             0.2098              0.8663   
4            152.20       1575.0             0.1374            205.0000   

    concavity_worst   concave_points_worst   symmetry_worst  \
0            0.7119                 0.2654           0.4601   
1            0.2416               186.0000         275.0000   
2            0.4504               243.0000           0.3613   
3            0.6869                 0.2575           0.6638   
4            0.4000                 0.1625           0.2364   

    fractal_dimension_worst  
0                   0.11890  
1                   0.08902  
2                   0.08758  
3                 173.00000  
4                   0.07678  

[5 rows x 30 columns]

In [2]:
#separando entre camada de treino e teste 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df_input, df_output, test_size=0.25)

In [3]:
#importando o keras e classes para a construção da RNA
import keras
from keras.models import Sequential 
from keras.layers import Dense


Using TensorFlow backend.
C:\Users\gvini\Anaconda3\envs\deep-learning-env\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\gvini\Anaconda3\envs\deep-learning-env\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\gvini\Anaconda3\envs\deep-learning-env\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\gv

In [4]:
#construindo a RNA
#A classe sequntial é a base para construção de cada camada da rede
classificador = Sequential()

#adicionando a camada de entrada e a uma camada oculta 
classificador.add(Dense(units=16,activation='relu',
kernel_initializer='random_uniform', input_dim=30
))

#perceba que a cama de entrada(inpute_dim) possui 30 neuronios de entrada 
#e a primeira camda oculta possui 16(units)

#camada de saida com um neuronio(saida binaria)
classificador.add(Dense(units=1, activation='sigmoid'))

In [5]:
#compilando as camadas da rede
classificador.compile(optimizer='adam', loss='binary_crossentropy',metrics=['binary_accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [6]:
#treinando o classificador 
classificador.fit(X_train,y_train,batch_size=10,epochs=100)


Epoch 1/100
426/426 [==============================] - 1s 2ms/step - loss: 13.8135 - binary_accuracy: 0.5704
Epoch 2/100
426/426 [==============================] - 0s 211us/step - loss: 3.1779 - binary_accuracy: 0.7418
Epoch 3/100
426/426 [==============================] - 0s 183us/step - loss: 0.5532 - binary_accuracy: 0.7840
Epoch 4/100
426/426 [==============================] - 0s 187us/step - loss: 0.5036 - binary_accuracy: 0.7911
Epoch 5/100
426/426 [==============================] - 0s 195us/step - loss: 0.3568 - binary_accuracy: 0.8545
Epoch 6/100
426/426 [==============================] - 0s 206us/step - loss: 0.3156 - binary_accuracy: 0.8545 0s - loss: 0.3448 - binary_accuracy: 0.846
Epoch 7/100
426/426 [==============================] - 0s 223us/step - loss: 0.2708 - binary_accuracy: 0.8685
Epoch 8/100
426/426 [==============================] - 0s 189us/step - loss: 0.2955 - binary_accuracy: 0.8638
Epoch 9/100
426/426 [==============================] - 0s 201us/step - loss: 

426/426 [==============================] - 0s 194us/step - loss: 0.1897 - binary_accuracy: 0.9343
Epoch 72/100
426/426 [==============================] - 0s 234us/step - loss: 0.1865 - binary_accuracy: 0.9272
Epoch 73/100
426/426 [==============================] - 0s 215us/step - loss: 0.2151 - binary_accuracy: 0.9155
Epoch 74/100
426/426 [==============================] - 0s 241us/step - loss: 0.1714 - binary_accuracy: 0.9225
Epoch 75/100
426/426 [==============================] - 0s 236us/step - loss: 0.2767 - binary_accuracy: 0.9061
Epoch 76/100
426/426 [==============================] - 0s 225us/step - loss: 0.3368 - binary_accuracy: 0.9038
Epoch 77/100
426/426 [==============================] - 0s 243us/step - loss: 0.2933 - binary_accuracy: 0.9108
Epoch 78/100
426/426 [==============================] - 0s 204us/step - loss: 0.3510 - binary_accuracy: 0.8967
Epoch 79/100
426/426 [==============================] - 0s 220us/step - loss: 0.2925 - binary_accuracy: 0.9131
Epoch 80/100
4

In [7]:
#como a função de saida foi a sigmoid a rede esta devolvendo a probabilidade de ser 0 ou 1
previsoes = classificador.predict(X_test)
print(previsoes)

[[9.8675597e-01]
 [9.7838473e-01]
 [9.4254923e-01]
 [9.9725580e-01]
 [7.7827376e-01]
 [9.9914539e-01]
 [4.6906671e-01]
 [9.9156392e-01]
 [2.4818736e-01]
 [9.3101406e-01]
 [1.2214053e-01]
 [6.8250859e-01]
 [9.9910402e-01]
 [1.2516975e-06]
 [2.6062131e-04]
 [1.7362833e-04]
 [1.0000000e+00]
 [4.5143563e-01]
 [1.1519194e-03]
 [9.7204417e-01]
 [9.9453580e-01]
 [5.2201772e-01]
 [1.4576316e-04]
 [9.8953629e-01]
 [9.9131244e-01]
 [3.5762787e-07]
 [2.0272279e-01]
 [9.9724245e-01]
 [2.8467035e-01]
 [9.1737634e-01]
 [1.5416172e-01]
 [2.3841858e-07]
 [1.2238741e-02]
 [0.0000000e+00]
 [9.9753106e-01]
 [5.7303905e-04]
 [0.0000000e+00]
 [9.8380214e-01]
 [9.9687135e-01]
 [9.9653184e-01]
 [0.0000000e+00]
 [9.9228060e-01]
 [9.4422841e-01]
 [9.9817431e-01]
 [8.9630014e-01]
 [1.9848725e-01]
 [9.9848557e-01]
 [9.8824489e-01]
 [0.0000000e+00]
 [8.7393421e-01]
 [1.4901161e-07]
 [6.5166777e-01]
 [4.0316582e-04]
 [1.7663836e-04]
 [9.9690485e-01]
 [5.4854316e-01]
 [9.9746829e-01]
 [1.4841855e-03]
 [0.0000000e+0

In [57]:
#transformando as probabilidades em 0 ou 1
previsoes = previsoes>0.5

### Metricas de avaliação do algoritimo ###

In [58]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
accuracy=classification_report(y_test, previsoes)
print(accuracy)


              precision    recall  f1-score   support

           0       0.60      0.98      0.74        46
           1       0.99      0.69      0.81        97

    accuracy                           0.78       143
   macro avg       0.79      0.83      0.78       143
weighted avg       0.86      0.78      0.79       143



In [59]:
confusion_matrix=confusion_matrix(y_test, previsoes)
print(confusion_matrix)

[[45  1]
 [30 67]]


In [60]:
#avaliando as metricas com keras
classificador.evaluate(X_test,y_test)

AttributeError: 'KerasClassifier' object has no attribute 'evaluate'

## Mais Camadas e os otimizadores ##
Agora o objetivo e aumentar a acuracia alterando as camadas e manipulando os otimizadores para atualização dos pesos.


In [ ]:
#adicionando mais uma camda oculta 

classificador = Sequential()

classificador.add(Dense(units=16,activation='relu',
kernel_initializer='random_uniform', input_dim=30
))

#nova camada
classificador.add(Dense(units=16,activation='relu',
kernel_initializer='random_uniform'
))

classificador.add(Dense(units=1, activation='sigmoid'))

#funções de ativação link: https://keras.io/activations/

In [ ]:
#criando um otimizador
adam = keras.optimizers.Adam(learning_rate=0.001,decay=0.0001,clipvalue=0.5)
#link: https://keras.io/optimizers/

In [ ]:
#compilando e treinando novamente
classificador.compile(optimizer=adam, loss='binary_crossentropy',metrics=['binary_accuracy'])
classificador.fit(X_train,y_train,batch_size=10,epochs=100)

In [ ]:
#avaliando as metricas com keras
classificador.evaluate(X_test,y_test)

In [ ]:
previsoes = classificador.predict(X_test)
previsoes = previsoes>0.5
print(classification_report(y_test, previsoes))

In [ ]:
#visualizando os pesos da primeira camada
pesos0 = classificador.layers[0].get_weights()
pesos1 = classificador.layers[1].get_weights()
pesos2 = classificador.layers[2].get_weights()

print(f'pesos0: {len(pesos0),type(pesos0)} \n pesos1: {len(pesos1),type(pesos1)} \n pesos2: {len(pesos2),type(pesos2)}')

In [ ]:
print(f'Pesos0:{pesos0[0].shape} \n Pesos1:{pesos1[0].shape} \n Pesos2:{pesos2[0].shape} ')

In [ ]:
print(pesos1[0])

In [ ]:
print(f'Unidade de Bias: \n {pesos0[1]}')

### É importante perceber a organização das entradas de cada neurônio por camada e seus pesos a partir dos valores acima. ###

# k-fold cross validation # 
documentação: 

keras:https://keras.io/scikit-learn-api/

sklearn:https://scikit-learn.org/stable/modules/cross_validation.html 

In [ ]:
#usando o keras classifier para classicar os dados através de uma função 
import keras
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

def cria_rede():
    classificador = Sequential()
    classificador.add(Dense(units=16,activation='relu',
    kernel_initializer='random_uniform', input_dim=30
    ))
    #nova camada
    classificador.add(Dense(units=16,activation='relu',
    kernel_initializer='random_uniform'
    ))
    #camada de saida
    classificador.add(Dense(units=1, activation='sigmoid'))
    adam = keras.optimizers.Adam(learning_rate=0.001,decay=0.0001,clipvalue=0.5)
    classificador.compile(optimizer=adam, loss='binary_crossentropy',metrics=['binary_accuracy'])
    
    return classificador 
    

In [ ]:
classificador = KerasClassifier(build_fn=cria_rede, epochs=100, batch_size=10)

In [ ]:
scores = cross_val_score(classificador , df_input, df_output, cv=10, scoring= 'accuracy')
#nesse caso o parametro scoring esta no default que é a acuracia

In [ ]:
scores

In [ ]:
print(f' media: {scores.mean()} e std:{scores.std()}')

Nesse bloco apenas foi usada a classe kerasClassifier para treinar a rede fazendo o "fitting" dos dados por meio de uma rede construida em uma função, além da vaidação cruzada.

## Overfitting ##
Acontece quando a rede se adapta demais a base de dados de treinamento gerando dessa forma um classificador com baixa generalização para os dados em questão.
Uma tecnica para previnir o overfitting é o dropout, basicamente será escolhido aleatoriamente neuronios da camada de entrada para serem zerados.

In [ ]:
#reescrevendo a função de criação da rede e adicionando o dropout
from keras.layers import Dropout

def cria_rede_dropout():
    classificador = Sequential()
    classificador.add(Dense(units=16,activation='relu',
    kernel_initializer='random_uniform', input_dim=30
    ))
    #adcionando Dropout a camada de entrada
    classificador.add(Dropout(0.2))
    #nova camada
    classificador.add(Dense(units=16,activation='relu',
    kernel_initializer='random_uniform'
    ))
      #adcionando Dropout a camada oculta
    classificador.add(Dropout(0.2))
    #camada de saida
    classificador.add(Dense(units=1, activation='sigmoid'))
    adam = keras.optimizers.Adam(learning_rate=0.001,decay=0.0001,clipvalue=0.5)
    classificador.compile(optimizer=adam, loss='binary_crossentropy',metrics=['binary_accuracy'])
    
    return classificador 


In [ ]:
novo_classificador = KerasClassifier(build_fn=cria_rede_dropout, epochs=100, batch_size=10)
novo_scores = cross_val_score(novo_classificador , df_input, df_output, cv=10, scoring= 'accuracy')

In [61]:
novo_scores

array([0.73684211, 0.84210526, 0.89473684, 0.78947368, 0.87719298,
       0.89473684, 0.92982456, 0.92982456, 0.80701754, 0.92857143])

In [62]:
print(f' media: {scores.mean()} e std:{scores.std()}')

 media: 0.8295112781954888 e std:0.04780044758870955


Com o Dropout perceba que o desvio padrão e consequentemente as variância das acuracias é menor.